<div id="page-wrapper">

  <div class="row">
    <div class="col-lg-12">
      <h1>GOBIERNO Y TRANSPARENCIA
        <small>Haciendo m&aacute;s claro el futuro</small>
      </h1>
      <ol class="breadcrumb">
        <li class="active">
          <!--<i class="fa fa-dashboard"></i>-->
          Porque los gobiernos democráticos deben a través de la tecnología, brindar a sus ciudadanos la información
          necesaria
          para ser transparentes. Para que el ciudadano común, impulse el esfuerzo de su país adelante.
        </li>
      </ol>

      <!--Imagen de gobierno abierto-->
      <div class="mainImg"></div>

    </div>
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-lg-12">
      <div class="page-header marginTop20"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-4">
      <p class="pCenter">
        <!--<i class="fa fa-dashboard"></i>-->
        Porque los gobiernos democráticos deben a través de la tecnología, brindar a sus ciudadanos la información
        necesaria
        para ser transparentes. Para que el ciudadano común, impulse el esfuerzo de su país adelante.
      </p>
    </div>
    <div class="col-lg-2">
      <div class="bigCircle">20%<span>Transparencia</span></div>
    </div>
    <div class="col-lg-4">
      <p class="pCenter">
        <!--<i class="fa fa-dashboard"></i>-->
        Porque los gobiernos democráticos deben a través de la tecnología, brindar a sus ciudadanos la información
        necesaria
        para ser transparentes. Para que el ciudadano común, impulse el esfuerzo de su país adelante.
      </p>
    </div>
    <div class="col-lg-1"></div>

    <div class="row">
      <div class="col-lg-12">
        <div class="page-header marginTop20"></div>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-lg-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-4">
              <i class="fa fa-comments fa-5x"></i>
            </div>
            <div class="col-xs-8 text-right">
              <p class="announcement-heading">+456</p>

              <p class="announcement-text">Visitas Diarias</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-4">
              <i class="fa fa-check fa-5x"></i>
            </div>
            <div class="col-xs-8 text-right">
              <p class="announcement-heading">125</p>

              <p class="announcement-text">Gobiernos registrados</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-4">
              <i class="fa fa-tasks fa-5x"></i>
            </div>
            <div class="col-xs-8 text-right">
              <p class="announcement-heading">18</p>

              <p class="announcement-text">Numero de Proyectos</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-lg-12">
      <div class="page-header marginTop20"></div>
    </div>
  </div>


</div>
<!-- /#page-wrapper -->
